### ISSUE TITLE
向模板填充数据建议直接替换原目标容器

### ISSUE THREAD

**Issue by Andykeh** [zhangshaolong/simplite#1]
建议吧  target 和  template 合二为一，吧处理好的数据直接替换原模板块 这样就不用再页面上单独定义一个容器用来填充处理好的数据了。
模板编译已经缓存到compileCache，只需要 把id选择器定义到模板块父容器上，然后将处理好的数据再插入该容器就好了，这样从处理好的页面dom也比较清晰只保留了处理好的数据。

**Comment by zhangshaolong** [comment]
谢谢你的建议，最近2天会局部重构，也请多多提些宝贵意见和建议
